[features]
seeds = false
skip-lint = false
[programs.localnet]
first_anchor_program = "AProvwUdgUYhvLJjejBH5Ba7LfS8wKAbj5KmFNmf2FNt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "Autnq8zhvT3RRTwJsboJkjn7FjXZomW2ByUKbXTEbRMy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
